Document: sonyfsfn
Title: Debian sonyfsfn Manual
Author: <insert document author here>
Abstract: This manual describes what sonyfsfn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sonyfsfn/sonyfsfn.sgml.gz

Format: postscript
Files: /usr/share/doc/sonyfsfn/sonyfsfn.ps.gz

Format: text
Files: /usr/share/doc/sonyfsfn/sonyfsfn.text.gz

Format: HTML
Index: /usr/share/doc/sonyfsfn/html/index.html
Files: /usr/share/doc/sonyfsfn/html/*.html

  
